---
# Source: mychart/templates/preview.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment-pr-2-preview
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/sveltekit-web3auth-template.git
    targetRevision: feat/shared-workflows
    helm:
      version: v3
  destination:
    namespace: environment-pr-2-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
