---
# Source: example-policy-service-preview/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-policy-service-pr-45-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/CloudNativeEntrepreneur/example-policy-service.git
    targetRevision: renovate/eslint-plugin-jest-27.x
    helm:
      version: v3
      values: |
        image:
          tag: pr-45-ccf5ba5c6ac7b469f9a4998f1efc145ab11c2779
  destination:
    namespace: example-policy-service-pr-45-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Source: example-policy-service-preview/templates/environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-policy-service-pr-45-preview-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/environment.git
    targetRevision: v0.4.0
    helm:
      version: v3
  destination:
    namespace: example-policy-service-pr-45-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
