---
# Source: example-hasura/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hasura-pr-11-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/CloudNativeEntrepreneur/example-hasura.git
    targetRevision: feat/shared-workflows
    helm:
      version: v3
      values: |
        image:
          tag: pr-11-51c163337da70052ed92bf038e5702e7491241dc
  destination:
    namespace: example-hasura-pr-11-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Source: example-hasura/templates/environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hasura-pr-11-preview-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/environment.git
    targetRevision: v0.4.0
    helm:
      version: v3
  destination:
    namespace: example-hasura-pr-11-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
