---
# Source: example-policy-service-preview/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hasura-projections-service-pr-69-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/example-hasura-projections-service.git
    targetRevision: renovate/lint-staged-13.x
    helm:
      version: v3
      values: |
        image:
          tag: pr-69-a1cffece35a3f4e26c3c725cdc65b517925ae2fb
  destination:
    namespace: example-hasura-projections-service-pr-69-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
# Source: example-policy-service-preview/templates/environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hasura-projections-service-pr-69-preview-env
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/environment.git
    targetRevision: v0.2.0
    helm:
      version: v3
  destination:
    namespace: example-hasura-projections-service-pr-69-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
