---
# Source: example-todo-model-service-preview/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-todo-model-service-pr-73-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/example-todo-model-service.git
    targetRevision: feat/integration-tests
    helm:
      version: v3
      values: |
        image:
          tag: pr-73-a66a9aca8b16d51b20894e94d9b7230f7090ff01
  destination:
    namespace: example-todo-model-service-pr-73-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
# Source: example-todo-model-service-preview/templates/environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-todo-model-service-pr-73-preview-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/environment.git
    targetRevision: v0.2.0
    helm:
      version: v3
  destination:
    namespace: example-todo-model-service-pr-73-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Source: example-todo-model-service-preview/templates/sourced-db.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-todo-model-service-pr-73-preview-sourced-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: example-preview-envs
  source:
    path: charts/sourced-db
    repoURL: https://github.com/cloudnativeentrepreneur/sourced-db.git
    targetRevision: HEAD
    helm:
      version: v3
  destination:
    namespace: example-todo-model-service-pr-73-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
