---
# Source: example-hasura-projections-service/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hasura-projections-service-pr-70-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/CloudNativeEntrepreneur/example-hasura-projections-service.git
    targetRevision: feat/shared-workflows
    helm:
      version: v3
      values: |
        image:
          tag: pr-70-892b0b0889c41d700e94b2bff1ab3773c73c0884
  destination:
    namespace: example-hasura-projections-service-pr-70-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Source: example-hasura-projections-service/templates/environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hasura-projections-service-pr-70-preview-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/environment.git
    targetRevision: v0.4.0
    helm:
      version: v3
  destination:
    namespace: example-hasura-projections-service-pr-70-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
