---
# Source: sveltekit-web3auth-template/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sveltekit-web3auth-template-pr-79-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/CloudNativeEntrepreneur/sveltekit-web3auth-template.git
    targetRevision: renovate/eslint-monorepo
    helm:
      version: v3
      values: |
        image:
          tag: pr-79-941190e9548139461ae145c70d475587e131e653
  destination:
    namespace: sveltekit-web3auth-template-pr-79-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Source: sveltekit-web3auth-template/templates/environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sveltekit-web3auth-template-pr-79-preview-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/environment.git
    targetRevision: v0.5.3
    helm:
      version: v3
  destination:
    namespace: sveltekit-web3auth-template-pr-79-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
