---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-ui-preview-pr-53
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/sveltekit-web3auth-template.git
    targetRevision: feat/previews-2
    helm:
      version: v3
      values: |
        image:
          tag: pr-53
  destination:
    namespace: example-ui-preview-pr-53
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-ui-preview-pr-53-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: resources/helm/preview
    repoURL: https://github.com/cloudnativeentrepreneur/example-preview-envs.git
    targetRevision: HEAD
    helm:
      version: v3
  destination:
    namespace: example-ui-preview-pr-53
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true