---
# Source: sveltekit-web3auth-template/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sveltekit-web3auth-template-pr-68-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/CloudNativeEntrepreneur/sveltekit-web3auth-template.git
    targetRevision: renovate/postcss-load-config-4.x
    helm:
      version: v3
      values: |
        image:
          tag: pr-68-f651f52eb84792432cd308258f52eb809d1c8902
  destination:
    namespace: sveltekit-web3auth-template-pr-68-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Source: sveltekit-web3auth-template/templates/environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sveltekit-web3auth-template-pr-68-preview-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/environment.git
    targetRevision: v0.4.0
    helm:
      version: v3
  destination:
    namespace: sveltekit-web3auth-template-pr-68-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
