---
# Source: web3auth-service/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web3auth-service-pr-67-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/CloudNativeEntrepreneur/web3auth-service.git
    targetRevision: renovate/eslint-plugin-svelte3-3.x
    helm:
      version: v3
      values: |
        image:
          tag: pr-67-82a2bd29ccd2e35e7010e6b05f73fa5491b1930a
  destination:
    namespace: web3auth-service-pr-67-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Source: web3auth-service/templates/environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web3auth-service-pr-67-preview-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/environment.git
    targetRevision: v0.4.0
    helm:
      version: v3
  destination:
    namespace: web3auth-service-pr-67-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
